export default fonts = {
  HeadAuth: {
    fontFamily: 'AkayaKanadaka-Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 50,
    lineHeight: 59.8,
  },
    subHead: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 25,
      lineHeight: 29,
    },
    fishDetail: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 32,
      lineHeight: 38,
    },
    subHeadHistory: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 30,
      lineHeight: 35,
    },
    text: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 12,
      lineHeight: 14,
      
    },
    buttonText: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 18,
      lineHeight: 21,
    },

    placeHolder: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      // fontWeight: 400,
      fontSize: 14,
      lineHeight: 17,
    },
    placeHolder2: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 14,
      lineHeight: 17,
    },
    sub_head_small: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 10,
      lineHeight: 11,
    },
    headSettings: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 35,
      lineHeight: 40,
    },
    subscriptionTrial_head: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      // fontWeight: 400,
      fontSize: 20,
      lineHeight: 23,
    },
    trial_head: {
      fontFamily: 'Montserrat-Regular',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: 46,
      lineHeight: 57,
    },
    trial_head_sub: {
      fontFamily: 'Montserrat-Regular',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: 23,
      lineHeight: 30,
    },

    notificationTime: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 700,
      fontSize: 10,
      lineHeight: 12,
    },
    helpPlaceholder: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      // fontWeight: 400,
      fontSize: 16,
      lineHeight: 19,
    },
  };