export default fonts = {
  HeadAuth: {
    fontFamily: 'AkayaKanadaka-Regular',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 46,
    lineHeight: 55.8,
  },
    subHead: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 24,
      lineHeight: 27,
    },
    fishDetail: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 28,
      lineHeight: 34,
    },
    subHeadHistory: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 28,
      lineHeight: 33,
    },
    text: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 12,
      lineHeight: 14,
      
    },
    buttonText: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 17,
      lineHeight: 20,
    },

    placeHolder: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      // fontWeight: 400,
      fontSize: 14,
      lineHeight: 17,
    },
    placeHolder2: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 15,
      lineHeight: 17,
    },
    sub_head_small: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 12,
      lineHeight: 12,
    },
    headSettings: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 33,
      lineHeight: 38,
    },
    subscriptionTrial_head: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      // fontWeight: 400,
      fontSize: 20,
      lineHeight: 23,
    },
    trial_head: {
      fontFamily: 'Montserrat-Regular',
      fontStyle: 'normal',
      // fontWeight: 600,
      fontSize: 42,
      lineHeight: 53,
    },
    trial_head_sub: {
      fontFamily: 'Montserrat-Regular',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: 23,
      lineHeight: 28,
    },

    notificationTime: {
      fontFamily: 'Montserrat-Bold',
      // fontStyle: 'normal',
      fontWeight: 700,
      fontSize: 11,
      lineHeight: 12,
    },
    helpPlaceholder: {
      fontFamily: 'AkayaKanadaka-Regular',
      fontStyle: 'normal',
      // fontWeight: 400,
      fontSize: 16,
      lineHeight: 19,
    },
  };