export default fonts = {
  HeadAuth: {
    fontFamily: 'Akaya Kanadaka',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: 50,
    lineHeight: 59,
  },
    subHead: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 25,
      lineHeight: 29,
    },
    subHeadHistory: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 30,
      lineHeight: 35,
    },
    text: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 12,
      lineHeight: 14,
      
    },
    buttonText: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 18,
      lineHeight: 22,
    },
    placeHolder: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      // fontWeight: 400,
      fontSize: 14,
      lineHeight: 17,
    },
    placeHolder2: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 14,
      lineHeight: 17,
    },
    sub_head_small: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 10,
      lineHeight: 12,
    },
    headSettings: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 35,
      lineHeight: 40,
    },
    subscriptionTrial_head: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 20,
      lineHeight: 24,
    },
    trial_head: {
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: 50,
      lineHeight: 61,
    },
    trial_head_sub: {
      fontFamily: 'Montserrat',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: 25,
      lineHeight: 30,
    },
    subscriptionTrial_head: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: 20,
      lineHeight: 24,
    },
    notificationTime: {
      fontFamily: 'Akaya Kanadaka',
      fontStyle: 'normal',
      fontWeight: 700,
      fontSize: 10,
      lineHeight: 12,
    },
  };